name: appsearchjob
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  amplify_flutter: ^1.3.0
  amplify_auth_cognito: ^1.3.0
  email_validator: ^2.0.1
  flutter_secure_storage: ^9.2.2
  provider: ^6.0.3
  flutter_marquee: ^2.0.1
  shared_preferences: ^2.3.4
  amplify_secure_storage: ^0.4.4
  http: ^1.2.2
  amplify_datastore: ^1.7.0
  amazon_cognito_identity_dart_2: ^3.7.0
  amplify_api: ^1.8.0
  onesignal_flutter: ^5.2.9
  intl: ^0.20.0
  calendar_date_picker2: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/congviec.jpg